[package]
name = "ida-c-splitter"
version = "0.1.0"
edition = "2024"
default-run = "ida-c-splitter"

[dependencies]
memchr = "2.7.6"
memmap2 = "0.9.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
